openapi: 3.0.0
info:
  title: OIF API
  version: 0.1.0
  description: |-
    API specifications for OIF protocol covering quote generation and intent submission.
    Amount fields are strings representing integers (e.g., uint256) to preserve precision across transports.
servers:
  - url: https://api.example.com
tags:
  - name: quote
    description: Quote generation
  - name: intent
    description: Intent submission
paths:
  /v1/quote:
    post:
      summary: Generate executable quotes for requested outputs given available inputs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetQuoteRequest'
      responses:
        '200':
          description: Quotes successfully generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuoteResponse'
        '400':
          description: Malformed request
        '422':
          description: Inputs cannot satisfy requested outputs
  /v1/intent:
    post:
      summary: Submit a previously quoted, signed order for execution.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntentRequest'
      responses:
        '200':
          description: Intent accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntentResponse'
        '400':
          description: Malformed request
        '422':
          description: Invalid signature or order
components:
  schemas:
    Address:
      type: string
      description: ERC-7930 interoperable address
    Amount:
      type: string
      description: Integer encoded as a string to preserve precision (e.g., uint256)
      pattern: ^[0-9]+$
    AssetLockReference:
      type: object
      description: Reference to a lock in a locking system
      properties:
        kind:
          type: string
          description: Lock type identifier
          enum:
            - the-compact
            - rhinestone
        params:
          $ref: '#/components/schemas/Record<string,unknown>'
          description: Lock-specific parameters
      required:
        - kind
    AvailableInput:
      type: object
      description: Available input from a user
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        asset:
          $ref: '#/components/schemas/Address'
        lock:
          $ref: '#/components/schemas/AssetLockReference'
        user:
          $ref: '#/components/schemas/Address'
      required:
        - amount
        - asset
        - user
    Eip712Order:
      type: object
      description: EIP-712 typed data for execution
      properties:
        domain:
          $ref: '#/components/schemas/Address'
        message:
          $ref: '#/components/schemas/Record<string,unknown>'
        primaryType:
          type: string
          description: Primary type of the EIP-712 message
      required:
        - domain
        - message
        - primaryType
    GetQuoteRequest:
      type: object
      description: Request for generating quotes
      properties:
        availableInputs:
          type: array
          description: Order of inputs is significant if preference is 'input-priority'
          items:
            $ref: '#/components/schemas/AvailableInput'
        minValidUntil:
          type: number
          description: Minimum validity timestamp (seconds)
        preference:
          $ref: '#/components/schemas/QuotePreference'
        requestedOutputs:
          type: array
          description: Requested outputs for the quote
          items:
            $ref: '#/components/schemas/RequestedOutput'
        user:
          $ref: '#/components/schemas/Address'
      required:
        - availableInputs
        - requestedOutputs
        - user
    GetQuoteResponse:
      type: object
      description: Response containing generated quotes
      properties:
        quotes:
          type: array
          description: Array of generated quotes
          items:
            $ref: '#/components/schemas/Quote'
      required:
        - quotes
    IntentRequest:
      type: object
      description: Request to submit an intent
      properties:
        order:
          $ref: '#/components/schemas/Record<string,unknown>'
          description: EIP-712 typed data for a gasless cross-chain order
        provider:
          type: string
          description: Provider identifier
        quoteId:
          type: string
          description: Optional quote identifier from a prior Get Quote response
        signature:
          $ref: '#/components/schemas/Record<string,unknown>'
      required:
        - order
        - provider
        - signature
    IntentResponse:
      type: object
      description: Response from intent submission
      properties:
        message:
          type: string
          description: Optional message for additional details on status
        order:
          $ref: '#/components/schemas/Record<string,unknown>'
        orderId:
          type: string
          description: Assigned order identifier if accepted
        status:
          type: string
          description: Human/machine readable status string
      required:
        - status
    Quote:
      type: object
      description: Quote information
      properties:
        details:
          $ref: '#/components/schemas/QuoteDetails'
        eta:
          type: number
          description: Estimated time of arrival (seconds)
        orders:
          type: array
          description: EIP-712 orders for execution
          items:
            $ref: '#/components/schemas/Eip712Order'
        provider:
          type: string
          description: Provider identifier
        quoteId:
          type: string
          description: Unique quote identifier
        validUntil:
          type: number
          description: Quote validity timestamp (seconds)
      required:
        - details
        - orders
        - provider
        - quoteId
    QuoteDetails:
      type: object
      description: Detailed information about a quote
      properties:
        availableInputs:
          type: array
          items:
            type: object
            properties:
              user:
                $ref: '#/components/schemas/Address'
              asset:
                $ref: '#/components/schemas/Address'
              amount:
                $ref: '#/components/schemas/Amount'
              lockType:
                type: string
                enum:
                  - the-compact
                description: If empty, the asset needs to be escrowed
            required:
              - user
              - asset
              - amount
        requestedOutputs:
          type: array
          description: Requested outputs in the quote
          items:
            $ref: '#/components/schemas/RequestedOutputDetails'
      required:
        - availableInputs
        - requestedOutputs
    QuotePreference:
      type: string
      enum:
        - price
        - speed
        - input-priority
        - trust-minimization
    Record<string,unknown>:
      type: object
      additionalProperties: true
    RequestedOutput:
      type: object
      description: Requested output for a receiver
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        asset:
          $ref: '#/components/schemas/Address'
        calldata:
          type: string
          description: Optional calldata describing how the receiver will consume the output
        receiver:
          $ref: '#/components/schemas/Address'
      required:
        - amount
        - asset
        - receiver
    RequestedOutputDetails:
      type: object
      description: Detailed information about requested outputs
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        asset:
          $ref: '#/components/schemas/Address'
        calldata:
          type: string
          description: Optional calldata
        user:
          $ref: '#/components/schemas/Address'
      required:
        - amount
        - asset
        - user
